(function(){
'use strict';
const SQ=window.__SQ;
const {STATES,MAPS,ASSET,day,days,record,pointsFor,render,player,save,syncHeader,miniMap}=SQ;
const SECTIONS=[{"id":1,"title":"Section 1 • Western States","confirmed":true,"status":"CURRENT • TEACHER CONFIRMED","states":[["Alaska","AK","Juneau"],["Hawaii","HI","Honolulu"],["Washington","WA","Olympia"],["Oregon","OR","Salem"],["California","CA","Sacramento"],["Idaho","ID","Boise"],["Nevada","NV","Carson City"],["Utah","UT","Salt Lake City"],["Arizona","AZ","Phoenix"]]},{"id":2,"title":"Section 2 • Mountain & Plains","confirmed":false,"status":"UPCOMING • PROVISIONAL","states":[["Montana","MT","Helena"],["Wyoming","WY","Cheyenne"],["Colorado","CO","Denver"],["New Mexico","NM","Santa Fe"],["North Dakota","ND","Bismarck"],["South Dakota","SD","Pierre"],["Nebraska","NE","Lincoln"],["Kansas","KS","Topeka"],["Oklahoma","OK","Oklahoma City"],["Texas","TX","Austin"]]},{"id":3,"title":"Section 3 • Central & South","confirmed":false,"status":"UPCOMING • PROVISIONAL","states":[["Minnesota","MN","Saint Paul"],["Iowa","IA","Des Moines"],["Missouri","MO","Jefferson City"],["Arkansas","AR","Little Rock"],["Louisiana","LA","Baton Rouge"],["Wisconsin","WI","Madison"],["Illinois","IL","Springfield"],["Mississippi","MS","Jackson"],["Alabama","AL","Montgomery"],["Tennessee","TN","Nashville"]]},{"id":4,"title":"Section 4 • Great Lakes & Southeast","confirmed":false,"status":"UPCOMING • PROVISIONAL","states":[["Michigan","MI","Lansing"],["Indiana","IN","Indianapolis"],["Ohio","OH","Columbus"],["Kentucky","KY","Frankfort"],["West Virginia","WV","Charleston"],["Virginia","VA","Richmond"],["North Carolina","NC","Raleigh"],["South Carolina","SC","Columbia"],["Georgia","GA","Atlanta"],["Florida","FL","Tallahassee"]]},{"id":5,"title":"Section 5 • Northeast","confirmed":false,"status":"UPCOMING • PROVISIONAL","states":[["Pennsylvania","PA","Harrisburg"],["Maryland","MD","Annapolis"],["Delaware","DE","Dover"],["New Jersey","NJ","Trenton"],["New York","NY","Albany"],["Connecticut","CT","Hartford"],["Rhode Island","RI","Providence"],["Massachusetts","MA","Boston"],["Vermont","VT","Montpelier"],["New Hampshire","NH","Concord"],["Maine","ME","Augusta"]]}];
let section=SECTIONS[0],run=null,typed='';
const $s=s=>document.querySelector(s);
const norm=v=>(v||'').trim().toLowerCase().replace(/\s+/g,' ');
function stateObj(name){return STATES.find(s=>s.name===name);}
function sectionHome(){render(`<div class="eyebrow">WEST → EAST</div><h1 class="page-title">School Study</h1><p class="sub">Choose the map section Luke is practicing.</p><div class="section-grid">${SECTIONS.map(s=>`<button class="section-card ${s.confirmed?'confirmed':''}" data-school="section" data-id="${s.id}"><b>${s.title}</b><small>${s.status}</small><small>${s.states.length} states</small></button>`).join('')}</div><div class="info-strip"><b>Section 1</b> matches Luke’s current teacher sheet exactly. Sections 2–5 are non-overlapping placeholders and can be replaced as new sheets come home.</div>`,'school');}
function openSection(id){section=SECTIONS.find(s=>s.id===+id)||SECTIONS[0];render(`<div class="toolbar"><button class="soft" data-school="home">← Sections</button><span class="pill">${section.confirmed?'CONFIRMED':'UPCOMING'}</span></div><h1 class="page-title">${section.title}</h1><div>${section.states.map(x=>`<span class="school-chip">${x[0]}</span>`).join('')}</div><div class="school-skills"><button class="school-skill" data-school="learn"><b>📚 Learn Set</b><small>State • abbreviation • capital</small></button><button class="school-skill" data-school="start" data-mode="capital"><b>✏️ Spell Capitals</b><small>State Quest keyboard, no predictions</small></button><button class="school-skill" data-school="start" data-mode="state"><b>🔤 Spell States</b><small>State Quest keyboard, no predictions</small></button><button class="school-skill" data-school="start" data-mode="abbr"><b>🔡 Abbreviations</b><small>Type the 2-letter code</small></button><button class="school-skill" data-school="shapes"><b>🧩 State Shapes</b><small>Uses the same shapes as the main game</small></button><button class="school-skill" data-school="map"><b>🗺️ Map Test</b><small>Tap the state in its real position</small></button><button class="school-skill" data-school="start" data-mode="mixed"><b>🎯 School Test</b><small>Spelling + abbreviations + shapes + map</small></button></div>`,'school');}
function learn(){render(`<div class="toolbar"><button class="soft" data-school="section" data-id="${section.id}">← ${section.title}</button></div><table class="school-table"><tr><th>State</th><th>Abbr.</th><th>Capital</th></tr>${section.states.map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join('')}</table>`,'school');}
function keyboard(answer){return `<div id="school-display" class="school-display">${typed||'&nbsp;'}</div><div class="qwerty"><div class="qrow">${'QWERTYUIOP'.split('').map(key).join('')}</div><div class="qrow r2">${'ASDFGHJKL'.split('').map(key).join('')}</div><div class="qrow r3">${'ZXCVBNM'.split('').map(key).join('')}</div><div class="qrow"><button class="qkey back" data-school="back">⌫</button><button class="qkey space" data-school="key" data-key=" ">SPACE</button></div></div><button class="primary" data-school="check" data-answer="${answer}">CHECK ANSWER</button>`;}
function key(c){return `<button class="qkey" data-school="key" data-key="${c}">${c}</button>`;}
function start(mode){run={mode,items:[...section.states].sort(()=>Math.random()-.5),i:0,first:0};question();}
function question(){const x=run.items[run.i];typed='';if(run.mode==='mixed'){const t=run.i%5;if(t===3)return shapeQuestion(x);if(t===4)return mapQuestion(x);}let prompt,answer;if(run.mode==='capital'||run.mode==='mixed'&&run.i%5===0){prompt=`Spell the capital of ${x[0]}`;answer=x[2];}else if(run.mode==='state'||run.mode==='mixed'&&run.i%5===1){prompt=`Spell the state whose capital is ${x[2]}`;answer=x[0];}else{prompt=`Type the abbreviation for ${x[0]}`;answer=x[1];}render(`<div class="toolbar"><button class="soft" data-school="section" data-id="${section.id}">← School</button><span class="school-progress-pill">${run.i+1} / ${run.items.length}</span></div><div class="welcome"><div class="eyebrow">NO AUTOCORRECT • SPELLING COUNTS</div><h1>${prompt}</h1>${keyboard(answer)}<div id="school-feedback" class="school-note"></div></div>`,'school');}
function setDisplay(){const d=$s('#school-display');if(d)d.textContent=typed||' ';}
function addKey(k){typed+=k;setDisplay();}
function back(){typed=typed.slice(0,-1);setDisplay();}
function schoolAttempt(stateName,correct){const p=player(),s=stateObj(stateName);if(!p||!s)return;const r=record(p,s.abbr),today=day(),wasMastered=!!r.mastered;r.attempts++;r.lastDay=today;if(correct){r.correct++;r.consecutive++;if(!r.correctDays.includes(today))r.correctDays.push(today);r.correctDays.sort();if(r.correctDays.length>=3&&days(r.correctDays[0],today)>=4)r.mastered=true;}else{r.misses++;r.consecutive=0;r.lastMissDay=today;if(!wasMastered){r.correctDays=[];r.mastered=false;}else r.mastered=true;}save();syncHeader();}
function check(answer){const x=run.items[run.i],ok=norm(typed)===norm(answer);schoolAttempt(x[0],ok);if(ok){run.first++;$s('#school-feedback').innerHTML=`<div class="info-strip">✅ Exactly right: <b>${answer}</b></div>`;setTimeout(next,450);}else{$s('#school-feedback').innerHTML=`<div class="info-strip">✏️ Correct spelling: <b>${answer}</b>. Type it correctly once before moving on.</div>`;typed='';setDisplay();const b=$s('[data-school="check"]');b.dataset.school='retry';b.dataset.answer=answer;}}
function retry(answer){if(norm(typed)===norm(answer))setTimeout(next,250);else{typed='';setDisplay();$s('#school-feedback').innerHTML=`<div class="info-strip">Copy it exactly: <b>${answer}</b></div>`;}}
function next(){run.i++;if(run.i>=run.items.length)return finish();if(run.mode==='shapes')return shapeQuestion(run.items[run.i]);if(run.mode==='map')return mapQuestion(run.items[run.i]);question();}
function finish(){const p=player(),today=day(),score=run.first,total=run.items.length;let earned=0,isNewDay=false;if(p&&!p.completedDays.includes(today)){isNewDay=true;p.streak=days(p.lastDay,today)===1?p.streak+1:1;p.bestStreak=Math.max(p.bestStreak,p.streak);p.lastDay=today;p.completedDays.push(today);p.rounds++;if(p.rewards)earned=score===total?10:score>=Math.ceil(total*.8)?8:score>=Math.ceil(total*.6)?5:3;p.points+=earned;p.lifetimePoints+=earned;}if(p){p.history.push({id:'school-'+Date.now(),date:today,mode:'school',section:section.id,score,total,hints:0,earned});p.history=p.history.slice(-200);save();syncHeader();}render(`<div class="welcome"><div style="font-size:64px">🏆</div><h1>School set complete!</h1><p class="sub">${score} / ${total} correct on the first try.</p>${earned?`<div class="score-pill">+${earned} chore points</div>`:isNewDay?'':'<p class="sub">Today’s streak/reward was already claimed. Mastery practice still counted.</p>'}<button class="primary" data-school="section" data-id="${section.id}">Practice again</button></div>`,'school');}
function shapeMarkup(name){const s=stateObj(name);return s?miniMap(s):'';}
function shapeQuestion(x){const opts=[x,...section.states.filter(y=>y[0]!==x[0]).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);render(`<div class="toolbar"><button class="soft" data-school="section" data-id="${section.id}">← School</button><span class="school-progress-pill">${run.i+1} / ${run.items.length}</span></div><div class="welcome"><div class="eyebrow">STATE SHAPE</div><h1>Which state is this?</h1><div class="school-shape">${shapeMarkup(x[0])}</div><div class="school-choices">${opts.map(y=>`<button class="school-choice" data-school="shape-answer" data-answer="${x[0]}" data-choice="${y[0]}">${y[0]}</button>`).join('')}</div><div id="school-feedback"></div></div>`,'school');}
function shapes(){run={mode:'shapes',items:[...section.states].sort(()=>Math.random()-.5),i:0,first:0};shapeQuestion(run.items[0]);}
function shapeAnswer(answer,choice){const ok=answer===choice;schoolAttempt(answer,ok);if(ok){run.first++;setTimeout(next,300);}else $s('#school-feedback').innerHTML=`<div class="info-strip">That shape is <b>${answer}</b>. Study its outline and try the next one.</div>`;}
function overviewMap(target){return `<div class="school-region"><svg viewBox="0 0 820 500" role="img" aria-label="Unlabeled U.S. map">${STATES.map(s=>{const inSet=section.states.some(x=>x[1]===s.abbr);return `<path d="${ASSET.overview[s.abbr]}" class="school-map-path ${inSet?'active':''}" ${inSet?`data-school="map-answer" data-answer="${target}" data-choice="${s.name}"`:''}><title>${inSet?'Study section state':'Other state'}</title></path>`;}).join('')}</svg></div>`;}
function mapQuestion(x){render(`<div class="toolbar"><button class="soft" data-school="section" data-id="${section.id}">← School</button><span class="school-progress-pill">${run.i+1} / ${run.items.length}</span></div><div class="welcome"><div class="eyebrow">MAP TEST</div><h1>Tap ${x[0]}</h1><p class="sub">Only this study section is active. Alaska and Hawaii use the same insets as the main game.</p>${overviewMap(x[0])}<div id="school-feedback"></div></div>`,'school');}
function startMap(){run={mode:'map',items:[...section.states].sort(()=>Math.random()-.5),i:0,first:0};mapQuestion(run.items[0]);}
function mapAnswer(answer,choice,el){const ok=answer===choice;schoolAttempt(answer,ok);el.classList.add(ok?'good':'bad');if(ok){run.first++;setTimeout(next,350);}else $s('#school-feedback').innerHTML='<div class="info-strip">Not that one. Try again.</div>';}
function click(e){const b=e.target.closest('[data-school]');if(!b)return;const a=b.dataset.school;if(a==='home')sectionHome();else if(a==='section')openSection(b.dataset.id);else if(a==='learn')learn();else if(a==='start')start(b.dataset.mode);else if(a==='shapes')shapes();else if(a==='map')startMap();else if(a==='key')addKey(b.dataset.key);else if(a==='back')back();else if(a==='check')check(b.dataset.answer);else if(a==='retry')retry(b.dataset.answer);else if(a==='shape-answer')shapeAnswer(b.dataset.answer,b.dataset.choice);else if(a==='map-answer')mapAnswer(b.dataset.answer,b.dataset.choice,b);}
document.addEventListener('click',click);
window.SchoolStudy={home:sectionHome,learn,start,startMap,check,retry,sections:SECTIONS};
})();
